build: false

environment:
  MINICONDA: "C:\\Miniconda3-x64"
  matrix:    
    - PYTHON_VERSION: "3.7"
    - PYTHON_VERSION: "3.8"
    - PYTHON_VERSION: "3.9"

matrix:
  fast_finish: true

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - conda update --yes conda
  - conda create -n test-env --yes -c conda-forge python=%PYTHON_VERSION% codecov flake8 mypy numpy>=1.20 scikit-learn pytest-cov
  - conda activate test-env

test_script:
  - flake8 . --exclude doc --max-line-length=120
  # - mypy mapie examples --strict --config-file mypy.ini
  - pytest --cov-branch --cov=mapie --pyargs mapie

after_test:
  - codecov
