os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda update --yes conda
  - conda create -n test-env --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION codecov flake8 mypy numpy>=1.20 scikit-learn pytest-cov
  - conda activate test-env

script:
  - flake8 . --exclude doc --max-line-length=120
  # - mypy mapie examples --strict --config-file mypy.ini
  - pytest --cov-branch --cov=mapie --pyargs mapie

after_success:
  - codecov