name: mapie-notebooks
channels:
    - defaults
    - conda-forge
dependencies:
    - ipykernel=6.9.0
    - jupyter=1.0.0
    - jupyterlab=3.2.9
    - jupytext=1.13.6
    - matplotlib=3.5.1
    - nbconvert=6.4.0
    - pandas=1.3.5
    - pip=22.0.3
    - pip:
        - scikeras==0.4.1
    - python=3.10
    - scikit-learn=1.0.1
    - tensorflow=2.7.0
    - xgboost=1.5.1
