name: mapie
channels:
    - defaults
    - conda-forge
dependencies:
    - bump2version=1.0.1
    - flake8=3.9.0
    - mypy=0.800
    - numpydoc=1.1.0
    - pytest=6.2.2
    - pytest-cov=2.11.1
    - python=3.9.2
    - scikit-learn=0.24.1
    - sphinx=3.5.3
    - sphinx-gallery=0.8.2
    - sphinx_rtd_theme=0.5.2
    - twine=3.4.1
    - wheel=0.36.2