name: mapie-doc
channels:
    - defaults
    - conda-forge
dependencies:
    - numpydoc=1.1.0
    - sphinx=4.3.2
    - sphinx-gallery=0.10.1
    - sphinx_rtd_theme=1.0.0
    - typing_extensions=4.0.1
    - pandas
    - matplotlib
    - lightgbm